GET localhost:8080/items/all

###

POST localhost:8080/items
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="json"
Content-Type: application/json

{
  "title": "At.Long.Last.ASAP",
  "releaseYear": 2015,
  "format": "VINYL",
  "artists": [
    "A$AP Rocky"
  ],
  "tracks": [
    {
      "name": "Holy Ghost",
      "artists": [
        "A$AP Rocky"
      ]
    },
    {
      "name": "Canal St."
    }
  ],
  "tags": [
  ]
}

###

POST localhost:8080/items
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="json"
Content-Type: application/json

{
  "title": "Лічи до ста. Симфонія № 1",
  "releaseYear": 1994,
  "format": "CASSETTE",
  "artists": [
    "Oleksandr Yurchenko"
  ],
  "tracks": [
    {
      "name": "Симфонія №1",
      "artists": [
        "Oleksandr Yurchenko"
      ]
    }
  ],
  "tags": [
  ]
}

--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="test_image.jpg"
Content-Type: image/jpeg

< ./test_image.jpg

###

POST localhost:8080/ai/search?userQuery=скрябін
X_AI_CONVERSATION_ID: sashko
Content-Type: application/json

###

POST localhost:8080/ai/ask?question=розкажи+за+elton+john+альбом+хробак+не+використовуй+результати+з+rag+якщо+вони+невідповідні
X_AI_CONVERSATION_ID: sashko
Content-Type: application/json

###

POST localhost:8080/ai/ask
X_AI_CONVERSATION_ID: sashkoo
Content-Type: application/json

{
  "question": "чи доданий альбом виконавця Скрябін в базу, назва альбому: Казки"
}

###

POST localhost:8080/tags
Content-Type: application/json

[
{
  "name": "ukrainian rock"
}
]

###
GET https://api.discogs.com/releases/14193174

###
# Find similar tags to a free-text query (with optional maxDistance threshold; smaller is closer)
GET localhost:8080/tags/similar?query=ukr+rock&limit=5&maxDistance=0.3