Given the album title {title} by artists {artists}, format is {format}, analyze and categorize it using available tags.

Available tag categories:
{availableTagCategories}

Already existing tags to choose from for each category:
{availableTags}

Important Note! if your proposed tag does not exist:
- include it in a response and mark exists boolean as false
- pick a shade color for it (use CSS Named Colors palette); if tag does exist then leave shade as null